{% set name = "eumdac" %}
{% set version = "2.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc36fc364e2df0c5396051e8693a6cb2f0ae427e9d8869210bf4e5c86f4110bd

build:
  noarch: python
  entry_points:
    - eumdac = eumdac.cli:cli
  number: 0
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - requests >=2.5.0
    - pyyaml
    - urllib3 >=1.26, <2

  run:
    - python >=3.7
    - setuptools
    - requests >=2.5.0
    - pyyaml
    - urllib3

test:
  imports:
    - eumdac

about:
  home: https://user.eumetsat.int/resources/user-guides/eumetsat-data-access-client-eumdac-guide
  license: MIT
  license_file: LICENSE.txt
  summary: EUMETSAT Data Access Client
  description: |
    EUMDAC is the EUMETSAT Data Access Client. It provides simple access to the EUMETSAT data from a variety of
    satellite missions. As a Python library, it comes with many methods and helpers to use EUMETSATs APIs and
    services, like Data Store and Data Tailor. It also provides a variety of useful command-line utilities for data search,
    translation and processing.
  doc_url: https://usc.tools.eumetsat.int/docs/eumdac/v2.2.3/eumdac.html
  dev_url: https://gitlab.eumetsat.int/eumetlab/data-services/eumdac

extra:
  recipe-maintainers:
    - NiklasJordan
    - rafadelahoz
    - eumetsat-usc-das
