{% set name = "eumdac" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85359c42422815a0f2780bc988a95b3b7126f3ccdc98a9605d385b783044c2a7

build:
  noarch: python
  entry_points:
    - eumdac = eumdac.cli:cli
  number: 2
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - requests >=2.5.0
    - pyyaml
    - urllib3 >=1.26, <2
    - paho-mqtt

  run:
    - python >={{ python_min }}
    - setuptools
    - requests >=2.5.0
    - pyyaml
    - urllib3
    - paho-mqtt

test:
  requires:
    - python {{ python_min }}
  imports:
    - eumdac

about:
  home: https://user.eumetsat.int/resources/user-guides/eumetsat-data-access-client-eumdac-guide
  license: MIT
  license_file: LICENSE.txt
  summary: EUMETSAT Data Access Client
  description: |
    EUMDAC is the EUMETSAT Data Access Client. It provides simple access to the EUMETSAT data from a variety of
    satellite missions. As a Python library, it comes with many methods and helpers to use EUMETSATs APIs and
    services, like Data Store and Data Tailor. It also provides a variety of useful command-line utilities for data search,
    translation and processing.
  doc_url: https://usc.tools.eumetsat.int/docs/eumdac/
  dev_url: https://gitlab.eumetsat.int/eumetlab/data-services/eumdac

extra:
  recipe-maintainers:
    - NiklasJordan
    - rafadelahoz
    - eumetsat-usc-das
